http://localhost:1234/clients/?user=Emanuel&&pass=1234
####
http://localhost:1234/clients/1
####
http://localhost:1234/clients/rutas
####
POST http://localhost:1234/clients/login
Content-Type: application/json

{
    "user": "ester@gmail.com", 
    "pass": "1222432"
}

####

POST http://localhost:1234/clients
Content-Type: application/json

{
    "name": "Ester", 
    "email": "ester@gmail", 
    "password": "1222", 
    "tel": "a" 
}

####
PATCH http://localhost:1234/clients/1
Content-Type: application/json

{
    "firstname": "Emanuel",
    "lastname": "Ahumada",
    "email": "emaahmc08@gmail.com",
    "pass": "134",
    "calle": "Horacio Sanchez",
    "extN": "22",
    "intN": "12",
    "tel": "123214124",
    "col": "Solidaridad",
    "cp": "79020",
    "state": "San Luis Potosí",
    "city": "Ciudad Valles"
}