http://localhost:1234/clients/?user=Emanuel&&pass=1234
####
http://localhost:1234/
####
http://localhost:1234/clients/maps

####
POST http://localhost:1234/clients/login
Content-Type: application/json

{
    "user": "emaahmc08@gmail.com", 
    "pass": "12345"
}
####
POST http://localhost:1234/clients/validateemail
Content-Type: application/json

{
    "email": "ea8@gmail.com"
}
####

POST http://localhost:1234/clients
Content-Type: application/json

{
    "name": "Ester", 
    "email": "ester@gmail", 
    "password": "1222", 
    "tel": "a" 
}

####
PATCH http://localhost:1234/clients/1
Content-Type: application/json

{
    "firstname": "",
    "lastname": "",
    "email": "",
    "pass": "",
    "calle": "",
    "extN": "",
    "intN": "12",
    "tel": "123214124",
    "col": "Solidaridad",
    "cp": "79020",
    "state": "San Luis Potosí",
    "city": "Ciudad Valles"
}

####
GET http://localhost:1234/clients/desechos/7

####
POST http://localhost:1234/desechos
Content-Type: application/json

{
    "idClient": "1",
    "data": {
        "color": "Rojo",
        "numSerie": "358",
        "name": "Teclado",
        "marca": "Logi",
        "model": "3e3",
        "peso": "12.6",
        "date": "2024-05-06",
        "estado": "No sirve"
    }
}

####
POST http://localhost:1234/recolectores
Content-Type: application/json

{
    "claveTrabajador": "345",
    "responsable": "Emanuel Ahumada",
    "firstname": "Carlos",
    "lastname": "Perez",
    "email": "e@gmail.com",
    "pass": "1234",
    "confirm": "1234",
    "tel": "4811231234",
    "calle": "Horacio Sanchez",
    "extN": "22",
    "intN": "1",
    "col": "Solidaridad",
    "cp": "1234",
    "state": "San Luis Potosí",
    "city": "Ciudad Valles"
}

####
GET http://localhost:1234/desechos